version: '3.3'

services:
  backend:
    container_name: user-service
    build:
      context: .
    depends_on:
      - database
    restart: always
    ports:
      - '8080:8080'
    networks:
      - shared_network
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/user-db"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  database:
    container_name: database
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: 'user-db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root-pass'
    ports:
      - '5433:5432'
    volumes:
      - user-db:/var/lib/postgresql/data
    networks:
      - shared_network

  # Names of volumes
volumes:
  user-db:
networks:
  shared_network:
    external: true